# Generated by Django 4.2.7 on 2026-03-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffing", "0002_backfill_staff_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
